const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];
const ROLE_CODES = { ADMIN2026: "admin", TEAMS2026: "user", MEDIA2026: "media" };
let activeRole = "user";
let pendingRole = "user";
let calendarMonth = new Date(2026, 8, 1);

const tasks = [
  {id:1,task:"Dispatch call-for-tribute letters using the CLOGSAG protocol list",workstream:"Tributes",owner:"CLOGSAG National Secretariat",deadline:"2026-09-09",priority:"Urgent",status:"Completed",notes:"Confirm who will prepare each tribute."},
  {id:2,task:"Produce the CLOGSAG tribute list",workstream:"Tributes",owner:"CLOGSAG National Secretariat",deadline:"2026-09-09",priority:"Urgent",status:"Completed",notes:"Decision required on tribute contributors."},
  {id:3,task:"Prepare and dispatch two Winners Chapel letters",workstream:"Church",owner:"To be assigned",deadline:"2026-09-09",priority:"High",status:"Completed",notes:"Include church personalities from Ghana and Nigeria."},
  {id:4,task:"Prepare Accra Academy invitation list and hand it to Theo",workstream:"Invitations",owner:"Angelo",deadline:"2026-09-09",priority:"High",status:"Completed",notes:"Personal invitation workstream."},
  {id:5,task:"Finalise the family visitation letter list",workstream:"Family",owner:"To be assigned",deadline:"2026-09-10",priority:"Urgent",status:"Completed",notes:"List required for family letters."},
  {id:6,task:"Submit completed letters to CLOGSAG for dispatch",workstream:"Tributes",owner:"To be assigned",deadline:"2026-09-10",priority:"Urgent",status:"Completed",notes:"Include proof of dispatch."},
  {id:7,task:"Prepare the final list for family letters",workstream:"Family",owner:"To be assigned",deadline:"2026-09-12",priority:"High",status:"Completed",notes:"Check names and titles."},
  {id:8,task:"Collect biography, family information, photographs and funeral details",workstream:"Brochure",owner:"Editorial Team",deadline:"2026-09-15",priority:"High",status:"In progress",notes:"Content Collection I."},
  {id:9,task:"Collect officiating clergy, ministers and church information",workstream:"Church",owner:"Church-Related Subcommittee",deadline:"2026-09-19",priority:"High",status:"In progress",notes:"Content Collection II."},
  {id:10,task:"Confirm Pre-Burial, Burial, Thanksgiving and Graveside service details",workstream:"Order of Service",owner:"Burial and Thanksgiving Subcommittee",deadline:"2026-09-24",priority:"Urgent",status:"Not started",notes:"Private burial information must stay restricted."},
  {id:11,task:"Receive all stakeholder tributes",workstream:"Tributes",owner:"Tribute Team",deadline:"2026-09-24",priority:"Urgent",status:"In progress",notes:"Follow up with all outstanding organisations."},
  {id:12,task:"Collect and compile hymns, songs and lyrics",workstream:"Brochure",owner:"Editing Subcommittee",deadline:"2026-09-29",priority:"High",status:"Not started",notes:"Confirm correct sequence and wording."},
  {id:13,task:"Populate the first brochure draft",workstream:"Brochure",owner:"Editorial and Design Teams",deadline:"2026-10-02",priority:"Urgent",status:"Not started",notes:"Use all approved content received."},
  {id:14,task:"Review layout, biography, photographs, clergy, tributes and Order of Service",workstream:"Brochure",owner:"Funeral Central Coordination Team",deadline:"2026-10-05",priority:"High",status:"Not started",notes:"First formal review."},
  {id:15,task:"Complete corrections and collect outstanding content",workstream:"Brochure",owner:"Editorial Team",deadline:"2026-10-08",priority:"High",status:"Not started",notes:"Apply first review comments."},
  {id:16,task:"Final review and proofreading",workstream:"Brochure",owner:"Editing Subcommittee",deadline:"2026-10-09",priority:"Urgent",status:"Not started",notes:"Check names, titles, dates, spelling, sequence, photographs and lyrics."},
  {id:17,task:"Obtain final approval of the complete brochure",workstream:"Approval",owner:"Funeral Central Coordination Team",deadline:"2026-10-12",priority:"Urgent",status:"Not started",notes:"Record approval and final version."},
  {id:18,task:"Complete final artwork and pre-print checks",workstream:"Printing",owner:"Design Team",deadline:"2026-10-14",priority:"Urgent",status:"Not started",notes:"Submit approved artwork to printer."},
  {id:19,task:"Print the final funeral brochure",workstream:"Printing",owner:"To be assigned",deadline:"2026-10-15",priority:"Urgent",status:"Not started",notes:"Only the approved version may be printed."},
  {id:20,task:"Approve the official photograph, catchphrase and watermark",workstream:"Media",owner:"Communications and Design Teams",deadline:"2026-09-18",priority:"High",status:"In progress",notes:"Publish approved assets for all media partners."},
  {id:21,task:"Coordinate documentary and memorial website updates",workstream:"Media",owner:"Documentary and Communications Teams",deadline:"2026-10-15",priority:"Normal",status:"In progress",notes:"Use approved funeral content only."},
  {id:22,task:"Plan first aid, ambulance and paramedic support",workstream:"Operations",owner:"To be assigned",deadline:"2026-10-23",priority:"High",status:"Not started",notes:"Coverage required for funeral events."},
  {id:23,task:"Define the donations collection and accountability process",workstream:"Operations",owner:"To be assigned",deadline:"2026-10-16",priority:"High",status:"Not started",notes:"Name the responsible people."},
  {id:24,task:"Coordinate distribution of the funeral cloth",workstream:"Operations",owner:"Genevieve",deadline:"2026-10-23",priority:"Normal",status:"Not started",notes:"Confirm collection and distribution plan."},
  {id:25,task:"Prepare the funeral event layout",workstream:"Protocol",owner:"Protocol Team",deadline:"2026-10-23",priority:"High",status:"Not started",notes:"Account for the private burial arrangement."}
];

const funeralEvents = [
  {date:"2026-09-24",title:"Tributes due",type:"milestone"},{date:"2026-10-02",title:"First draft",type:"milestone"},{date:"2026-10-05",title:"First review",type:"milestone"},{date:"2026-10-09",title:"Final review",type:"milestone"},{date:"2026-10-12",title:"Final approval",type:"milestone"},{date:"2026-10-15",title:"Brochure printing",type:"milestone"},{date:"2026-10-30",title:"Vigil",type:"funeral"},{date:"2026-11-06",title:"Wake",type:"funeral"},{date:"2026-11-07",title:"Funeral",type:"funeral"},{date:"2026-11-08",title:"Thanksgiving",type:"funeral"}
];

const tributeParties = [];

const mediaFiles = [
  {name:"Official memorial portrait",category:"photograph",status:"Approved",available:true,src:"../web-pictures/headerfinal.png",href:"../web-pictures/headerfinal.png"},
  {name:"Official logo",category:"identity",status:"Approved",available:true,src:"../logo/logo_new.png",href:"../logo/logo_new.png"},
  {name:"One Week Remembrance booklet",category:"document",status:"Approved",available:true,src:null,href:"../booklet-assets/one-week-remembrance-service.pdf"},
  {name:"Order of Service",category:"document",status:"Approved",available:false,src:"../booklet-assets/order-of-service.jpg",href:"../booklet-assets/order-of-service.jpg"},
  {name:"Hymns",category:"document",status:"Approved",available:false,src:"../booklet-assets/hymns.jpg",href:"../booklet-assets/hymns.jpg"},
  {name:"Legacy photograph 01",category:"photograph",status:"Approved",available:true,src:"../web-pictures/F18_5598.JPG",href:"../web-pictures/F18_5598.JPG"},
  {name:"Legacy photograph 02",category:"photograph",status:"Approved",available:true,src:"../web-pictures/F18_9952.JPG",href:"../web-pictures/F18_9952.JPG"}
];

const savedTasks=localStorage.getItem("oaTeamsTasks");
if(savedTasks){try{const records=JSON.parse(savedTasks);if(Array.isArray(records)){tasks.splice(0,tasks.length,...records)}}catch{localStorage.removeItem("oaTeamsTasks")}}
const savedAvailability=JSON.parse(localStorage.getItem("oaMediaAvailability")||"{}");
mediaFiles.forEach(file=>{if(typeof savedAvailability[file.name]==="boolean")file.available=savedAvailability[file.name]});
function saveTasks(){localStorage.setItem("oaTeamsTasks",JSON.stringify(tasks))}
function saveMediaAvailability(){localStorage.setItem("oaMediaAvailability",JSON.stringify(Object.fromEntries(mediaFiles.map(file=>[file.name,file.available]))))}

function slug(value){return value.toLowerCase().replace(/\s+/g,"-")}
function escapeHtml(value){const div=document.createElement("div");div.textContent=String(value);return div.innerHTML}
function showStage(stage){$("#accessGate").hidden=stage!=="gate";$("#onboarding").hidden=stage!=="onboarding";$("#appShell").hidden=stage!=="app"}
function toast(message){const node=$("#toast");node.textContent=message;node.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.hidden=true,2600)}

$("#accessForm").addEventListener("submit",event=>{event.preventDefault();const code=new FormData(event.currentTarget).get("accessCode").trim().toUpperCase().replace(/[-\s]/g,"");if(!ROLE_CODES[code]){$("#accessMessage").textContent="That code was not recognised. Check it and try again.";$("#accessMessage").classList.add("error");return}pendingRole=ROLE_CODES[code];$("#assignedRole").textContent=pendingRole==="admin"?"Admin":pendingRole==="media"?"Media person":"Normal user";showStage("onboarding")});
$("#backToCode").addEventListener("click",()=>showStage("gate"));
async function registerProfile(profile){const response=await fetch("/api/users/",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(profile)});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Could not save this user");return payload.user}
$("#profileForm").addEventListener("submit",async event=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form),button=form.querySelector('button[type="submit"]');button.disabled=true;try{const profile=await registerProfile({name:data.get("fullName").trim(),phone:data.get("phone").trim(),role:pendingRole});localStorage.setItem("oaTeamsProfile",JSON.stringify(profile));applyProfile(profile);showStage("app")}catch(error){toast(error.message)}finally{button.disabled=false}});

function roleLabel(role){return role==="admin"?"Admin":role==="media"?"Media person":"Normal user"}
function applyProfile(profile){activeRole=profile.role;const initials=profile.name.split(/\s+/).slice(0,2).map(word=>word[0]).join("").toUpperCase()||"TM";$("#profileName").textContent=profile.name;$("#profileInitials").textContent=initials;$("#profileRole").textContent=roleLabel(activeRole);$("#currentMemberName").textContent=profile.name;$("#currentMemberAvatar").textContent=initials;$("#currentMemberRole").textContent=roleLabel(activeRole);applyRoleVisibility(activeRole)}
function applyRoleVisibility(role){const isAdmin=role==="admin",isMedia=role==="media";$("#accessNav").hidden=!isAdmin;$$(`.admin-action`).forEach(node=>node.hidden=!isAdmin);$$("#primaryNav button[data-view]").forEach(button=>button.hidden=isMedia&&button.dataset.view!=="media");if(isMedia)openView("media");else if(!isAdmin&&$("#accessView").classList.contains("active"))openView("tasks");renderTasks();renderMedia()}
function openView(name){$$('[data-view-panel]').forEach(panel=>{panel.classList.toggle("active",panel.dataset.viewPanel===name);panel.hidden=panel.dataset.viewPanel!==name});$$('#primaryNav button').forEach(button=>button.classList.toggle("active",button.dataset.view===name));const titles={tasks:"What needs to be done",media:"Media files",tributes:"Tributes",access:"Access control"};$("#viewTitle").textContent=titles[name];$("#sidebar").classList.remove("open");$("#menuButton").setAttribute("aria-expanded","false");window.scrollTo({top:0,behavior:"smooth"})}
$("#primaryNav").addEventListener("click",event=>{const button=event.target.closest("button[data-view]");if(button&&!button.hidden)openView(button.dataset.view)});
$("#menuButton").addEventListener("click",()=>{const open=$("#sidebar").classList.toggle("open");$("#menuButton").setAttribute("aria-expanded",String(open))});
$("#signOut").addEventListener("click",()=>{localStorage.removeItem("oaTeamsProfile");location.reload()});

function renderStats(){const counts={total:tasks.length,completed:tasks.filter(t=>t.status==="Completed").length,progress:tasks.filter(t=>t.status==="In progress").length,overdue:tasks.filter(t=>new Date(t.deadline)<new Date()&&t.status!=="Completed").length};$("#taskStats").innerHTML=`<article><span>Total tasks</span><strong>${counts.total}</strong><small>Across all workstreams</small></article><article><span>In progress</span><strong>${counts.progress}</strong><small>Currently being worked on</small></article><article><span>Completed</span><strong>${counts.completed}</strong><small>Recorded in the plan</small></article><article><span>Past deadline</span><strong>${counts.overdue}</strong><small>Needs an update</small></article>`;const received=tributeParties.filter(p=>p.tribute==="Received").length;const sent=tributeParties.filter(p=>p.request==="Sent").length;$("#tributeStats").innerHTML=`<article><span>Interested parties</span><strong>${tributeParties.length}</strong><small>From the source register</small></article><article><span>Requests sent</span><strong>${sent}</strong><small>${tributeParties.length-sent} still to send</small></article><article><span>Tributes received</span><strong>${received}</strong><small>${tributeParties.length-received} outstanding</small></article><article><span>Attached files</span><strong>${tributeParties.reduce((sum,p)=>sum+p.files.length,0)}</strong><small>Across all records</small></article>`}

function renderCalendar(){const year=calendarMonth.getFullYear(),month=calendarMonth.getMonth();$("#calendarTitle").textContent=new Intl.DateTimeFormat("en-GH",{month:"long",year:"numeric"}).format(calendarMonth);const first=new Date(year,month,1),offset=(first.getDay()+6)%7,start=new Date(year,month,1-offset);const weekdays=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];let html=weekdays.map(day=>`<div class="calendar-weekday">${day}</div>`).join("");for(let index=0;index<42;index++){const date=new Date(start);date.setDate(start.getDate()+index);const iso=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;const items=[...tasks.filter(t=>t.deadline===iso).map(t=>({id:t.id,title:t.task,type:"task"})),...funeralEvents.filter(e=>e.date===iso)];const today=new Date(),isToday=date.toDateString()===today.toDateString();html+=`<div class="calendar-day ${date.getMonth()!==month?"outside":""} ${isToday?"today":""}"><span class="day-number">${date.getDate()}</span>${items.slice(0,3).map(item=>item.id?`<div class="calendar-event-row"><button class="calendar-event ${item.type}" data-calendar-task="${item.id}" title="Open ${escapeHtml(item.title)}">${escapeHtml(item.title)}</button><button class="calendar-share" data-share-task="${item.id}" type="button" aria-label="Share ${escapeHtml(item.title)} on WhatsApp" title="Share on WhatsApp">W</button></div>`:`<button class="calendar-event ${item.type}" title="${escapeHtml(item.title)}">${escapeHtml(item.title)}</button>`).join("")}${items.length>3?`<small>+${items.length-3} more</small>`:""}</div>`}$("#calendar").innerHTML=html}
$("#calendarPrev").addEventListener("click",()=>{calendarMonth=new Date(calendarMonth.getFullYear(),calendarMonth.getMonth()-1,1);renderCalendar()});
$("#calendarNext").addEventListener("click",()=>{calendarMonth=new Date(calendarMonth.getFullYear(),calendarMonth.getMonth()+1,1);renderCalendar()});
$("#calendarToday").addEventListener("click",()=>{calendarMonth=new Date();calendarMonth.setDate(1);renderCalendar()});
$("#calendar").addEventListener("click",event=>{const share=event.target.closest("[data-share-task]");if(share){shareTask(tasks.find(item=>item.id===Number(share.dataset.shareTask)));return}const button=event.target.closest("[data-calendar-task]");if(!button)return;const task=tasks.find(item=>item.id===Number(button.dataset.calendarTask));openModal("task",task,activeRole!=="admin")});

function taskMessage(task){const deadline=new Intl.DateTimeFormat("en-GH",{day:"numeric",month:"short",year:"numeric"}).format(new Date(task.deadline+"T12:00:00"));return `*Oko and Atteh - Work Item*\n\n*${task.task}*\nWorkstream: ${task.workstream}\nPerson in charge: ${task.owner}\nDeadline: ${deadline}\nPriority: ${task.priority}\nStatus: ${task.status}${task.notes?`\nNotes: ${task.notes}`:""}`}
function shareTask(task){if(!task)return;window.open(`https://wa.me/?text=${encodeURIComponent(taskMessage(task))}`,"_blank","noopener,noreferrer")}
function renderTasks(){const query=$("#taskSearch").value.toLowerCase(),filter=$("#taskStatusFilter").value,isAdmin=activeRole==="admin";const filtered=tasks.filter(item=>(filter==="all"||slug(item.status)===filter)&&`${item.task} ${item.owner} ${item.workstream}`.toLowerCase().includes(query));$("#taskTableBody").innerHTML=filtered.map(item=>`<tr><td>${escapeHtml(item.task)}</td><td>${escapeHtml(item.workstream)}</td><td>${escapeHtml(item.owner)}</td><td>${new Intl.DateTimeFormat("en-GH",{day:"numeric",month:"short",year:"numeric"}).format(new Date(item.deadline+"T12:00:00"))}</td><td><span class="priority priority-${slug(item.priority)}">${item.priority}</span></td><td><span class="status status-${slug(item.status)}">${item.status}</span></td><td>${escapeHtml(item.notes)}</td><td><div class="task-actions"><button class="whatsapp-button" type="button" data-share-task="${item.id}">WhatsApp</button>${isAdmin?`<button class="edit-button" type="button" data-edit-task="${item.id}">Edit</button>`:""}</div></td></tr>`).join("")||`<tr><td colspan="8">No tasks match this filter.</td></tr>`}
$("#taskSearch").addEventListener("input",renderTasks);$("#taskStatusFilter").addEventListener("change",renderTasks);
$("#shareTasks").addEventListener("click",()=>{const outstanding=tasks.filter(task=>task.status!=="Completed").sort((a,b)=>a.deadline.localeCompare(b.deadline));const dateFormat=new Intl.DateTimeFormat("en-GH",{day:"numeric",month:"short",year:"numeric"});const lines=outstanding.map((task,index)=>`${index+1}. ${task.task}\nPerson in charge: ${task.owner}\nDeadline: ${dateFormat.format(new Date(task.deadline+"T12:00:00"))}\nStatus: ${task.status}`);const message=`*Oko and Atteh - Outstanding Tasks*\n\n${lines.join("\n\n")}`;window.open(`https://wa.me/?text=${encodeURIComponent(message)}`,"_blank","noopener,noreferrer")});

function renderMedia(){const query=$("#mediaSearch").value.toLowerCase(),filter=$("#mediaFilters .active").dataset.filter,isAdmin=activeRole==="admin";const roleVisible=isAdmin?mediaFiles:activeRole==="media"?mediaFiles.filter(file=>file.available):mediaFiles;const visible=roleVisible.filter(file=>(filter==="all"||file.category===filter)&&file.name.toLowerCase().includes(query));$("#mediaCount").textContent=roleVisible.length;$("#mediaSharedCount").textContent=roleVisible.filter(file=>file.available).length;$("#mediaPrivateCount").textContent=isAdmin?roleVisible.filter(file=>!file.available).length:"0";$("#mediaGrid").innerHTML=visible.map(file=>`<article class="media-card"><div class="media-preview media-${file.category} ${file.src?"":"document-preview"}">${file.src?`<img src="${file.src}" alt="" loading="lazy">`:`<span class="document-mark">PDF</span>`}<span class="file-type">${file.category}</span>${isAdmin?`<span class="availability ${file.available?"available":"private"}">${file.available?"Shared":"Private"}</span>`:""}</div><div class="media-copy"><div class="media-card-heading"><div><h3>${escapeHtml(file.name)}</h3><p>${file.status}</p></div><span class="media-state ${file.available?"shared":"restricted"}">${file.available?"Media ready":"Admin only"}</span></div><div class="media-actions"><a class="media-view" href="${file.href}" target="_blank" rel="noopener">Open</a><a href="${file.href}" download>Download</a>${isAdmin?`<button class="media-access-button" type="button" data-toggle-media="${escapeHtml(file.name)}">${file.available?"Make private":"Share with media"}</button>`:""}</div></div></article>`).join("")||`<div class="media-empty"><strong>No files found</strong><span>Try another filter or search term.</span></div>`}
$("#mediaFilters").addEventListener("click",event=>{const button=event.target.closest("button");if(!button)return;$$('#mediaFilters button').forEach(item=>item.classList.toggle("active",item===button));renderMedia()});$("#mediaSearch").addEventListener("input",renderMedia);
$("#mediaUpload").addEventListener("change",event=>{[...event.target.files].forEach(file=>mediaFiles.unshift({name:file.name,category:file.type.startsWith("image/")?"photograph":"document",status:"Working",available:false,src:file.type.startsWith("image/")?URL.createObjectURL(file):null,href:"#"}));renderMedia();toast(`${event.target.files.length} media file${event.target.files.length===1?"":"s"} added for admin review`)});
$("#mediaGrid").addEventListener("click",event=>{const button=event.target.closest("[data-toggle-media]");if(!button||activeRole!=="admin")return;const file=mediaFiles.find(item=>item.name===button.dataset.toggleMedia);file.available=!file.available;saveMediaAvailability();renderMedia();toast(file.available?`${file.name} is now available to the media person`:`${file.name} is now admin only`)});

function attachmentMarkup(file){const name=typeof file==="string"?file:file.name;const href=typeof file==="string"?"":file.href;return `<span class="attachment-item"><span class="attachment-chip" title="${escapeHtml(name)}">${escapeHtml(name)}</span>${href?`<a class="attachment-download" href="${href}" download="${escapeHtml(name)}">Download</a>`:""}${activeRole==="admin"&&file.id?`<button class="attachment-edit" type="button" data-edit-attachment="${file.id}">Edit</button>`:""}</span>`}
function renderTributes(){const query=$("#tributeSearch").value.toLowerCase(),filter=$("#tributeStatusFilter").value;const visible=tributeParties.filter(p=>{const matches=filter==="all"||(filter==="not-recorded"&&(p.request==="Not recorded"||p.tribute==="Not recorded"))||(filter==="sent"&&p.request==="Sent")||(filter==="received"&&p.tribute==="Received");return matches&&`${p.name} ${p.phone}`.toLowerCase().includes(query)});$("#tributeTableBody").innerHTML=visible.map(p=>`<tr><td>${escapeHtml(p.name)}</td><td>${p.phone?escapeHtml(p.phone):"<small>Not provided</small>"}</td><td><span class="status status-${slug(p.request)}">${p.request}</span></td><td><span class="status status-${slug(p.tribute)}">${p.tribute}</span></td><td><div class="attachment-list">${p.files.length?p.files.map(attachmentMarkup).join(""):"<small>No files</small>"}</div></td><td><label class="tribute-file-label">+ Add files<input class="tribute-file-input" type="file" multiple data-party-id="${p.id}" accept="image/*,.pdf,.doc,.docx"></label></td></tr>`).join("")||`<tr><td colspan="6">No tribute records match this filter.</td></tr>`;renderStats()}
async function apiJson(url,options={}){const response=await fetch(url,{cache:"no-store",...options});let payload;try{payload=await response.json()}catch{throw new Error("Invalid server response ("+response.status+")")}if(!response.ok)throw new Error(payload.error||"Request failed ("+response.status+")");return payload}
async function syncTributes(){try{const [partyPayload,fileRecords]=await Promise.all([apiJson("/api/tributes/parties"),apiJson("/api/tributes/files")]);const parties=Array.isArray(partyPayload.parties)?partyPayload.parties:[];tributeParties.splice(0,tributeParties.length,...parties.map(party=>({...party,files:Array.isArray(fileRecords[String(party.id)])?fileRecords[String(party.id)]:[]})));renderTributes()}catch(error){console.error("tribute_sync_failed",error);toast("Tribute records could not be loaded. Please refresh and try again.")}}
$("#tributeSearch").addEventListener("input",renderTributes);$("#tributeStatusFilter").addEventListener("change",renderTributes);$("#tributeTableBody").addEventListener("change",async event=>{if(!event.target.matches(".tribute-file-input"))return;const input=event.target,party=tributeParties.find(p=>p.id===Number(input.dataset.partyId)),files=[...input.files];if(!party||!files.length)return;input.disabled=true;toast(`Uploading ${files.length} file${files.length===1?"":"s"}...`);try{for(const file of files){const formData=new FormData();formData.append("file",file);const payload=await apiJson(`/api/tributes/${party.id}/files`,{method:"POST",body:formData});party.files.push(payload.file)}renderTributes();toast(`Files uploaded for ${party.name}`)}catch(error){console.error("tribute_upload_failed",error);toast(error.message||"Upload failed. Please try again.")}finally{input.disabled=false;input.value=""}});
$("#tributeTableBody").addEventListener("click",event=>{const button=event.target.closest("[data-edit-attachment]");if(!button||activeRole!=="admin")return;const attachment=tributeParties.flatMap(party=>party.files).find(file=>file.id===button.dataset.editAttachment);if(attachment)openModal("attachment",attachment)});

function option(value,current){return `<option${value===current?" selected":""}>${value}</option>`}
function openModal(type,item=null,viewOnly=false){const task=item||{task:"",workstream:"",owner:"",deadline:"",priority:"Normal",status:"Not started",notes:""};const fields={task:`<label>Task<input name="task" value="${escapeHtml(task.task)}" required></label><div class="form-grid"><label>Workstream<input name="workstream" value="${escapeHtml(task.workstream)}" required></label><label>Person in charge<input name="owner" value="${escapeHtml(task.owner)}" required></label></div><div class="form-grid"><label>Deadline<input name="deadline" type="date" value="${task.deadline}" required></label><label>Priority<select name="priority">${["Normal","High","Urgent"].map(value=>option(value,task.priority)).join("")}</select></label></div><label>Status<select name="status">${["Not started","In progress","Completed","Blocked"].map(value=>option(value,task.status)).join("")}</select></label><label>Notes<textarea name="notes">${escapeHtml(task.notes)}</textarea></label>`,party:`<label>Person or organisation<input name="party" required></label><label>Phone number<input name="phone" type="tel"></label>`,attachment:`<label>Download name<input name="name" value="${escapeHtml(item?.name||"")}" required></label><label>Replace file <small>(optional)</small><input name="file" type="file" accept="image/*,.pdf,.doc,.docx"></label><p class="form-help">Leave the replacement empty to rename the existing upload only.</p>`,code:`<label>Role<select name="role"><option>Admin</option><option>Normal user</option><option>Media person</option></select></label><label>Internal label<input name="label" placeholder="Who is this code for?"></label>`};$("#recordForm").dataset.type=type;$("#recordForm").dataset.editId=item?String(item.id):"";$("#modalEyebrow").textContent=viewOnly?"Task details":type==="code"?"Access control":type==="attachment"?"Tribute file":item?"Update record":"New record";$("#modalTitle").textContent=type==="task"?(viewOnly?"Work item":item?"Update work item":"Add task"):type==="party"?"Add tribute party":type==="attachment"?"Edit uploaded file":"Generate access code";$("#modalSave").hidden=viewOnly;$("#modalSave").textContent=item?"Save changes":"Save";$("#modalFields").innerHTML=fields[type];if(viewOnly)$$("#modalFields input, #modalFields select, #modalFields textarea").forEach(control=>control.disabled=true);$("#recordModal").showModal()}
$("#addTask").addEventListener("click",()=>openModal("task"));$("#addTributeParty").addEventListener("click",()=>openModal("party"));$("#generateCode").addEventListener("click",()=>openModal("code"));
$("#taskTableBody").addEventListener("click",event=>{const share=event.target.closest("[data-share-task]");if(share){shareTask(tasks.find(item=>item.id===Number(share.dataset.shareTask)));return}const button=event.target.closest("[data-edit-task]");if(!button||activeRole!=="admin")return;openModal("task",tasks.find(item=>item.id===Number(button.dataset.editTask)))});
$("#recordForm").addEventListener("submit",async event=>{
  if(event.submitter?.value!=="save")return;
  event.preventDefault();
  const form=event.currentTarget,data=new FormData(form),type=form.dataset.type,saveButton=$("#modalSave");
  saveButton.disabled=true;
  try{
    if(type==="task"){
      const editId=Number(form.dataset.editId);
      const values={task:data.get("task"),workstream:data.get("workstream"),owner:data.get("owner"),deadline:data.get("deadline"),priority:data.get("priority"),status:data.get("status"),notes:data.get("notes")};
      if(editId){Object.assign(tasks.find(item=>item.id===editId),values);toast("Work item updated")}
      else{tasks.push({id:Date.now(),...values});toast("Task added to the master register")}
      saveTasks();renderTasks();renderCalendar();renderStats();
    }else if(type==="party"){
      const payload=await apiJson("/api/tributes/parties",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:data.get("party").trim(),phone:data.get("phone").trim()})});
      tributeParties.push({...payload.party,files:[]});
      renderTributes();
      toast("Party saved to the tribute register");
    }else if(type==="attachment"){
      const attachmentId=form.dataset.editId,formData=new FormData();
      formData.append("name",data.get("name").trim());
      const replacement=data.get("file");if(replacement?.size)formData.append("file",replacement);
      const payload=await apiJson(`/api/tributes/files/${attachmentId}/edit`,{method:"POST",body:formData});
      tributeParties.forEach(party=>{const index=party.files.findIndex(file=>file.id===attachmentId);if(index>=0)party.files[index]=payload.file});
      renderTributes();toast("Tribute file updated");
    }else{
      const code=`OA${Math.random().toString(36).slice(2,8).toUpperCase()}`;
      $("#codeList").insertAdjacentHTML("afterbegin",`<article><div><strong>${code}</strong><small>${escapeHtml(data.get("role"))} · ${escapeHtml(data.get("label")||"New code")}</small></div><span class="status active-status">Active</span></article>`);
      toast(`Access code ${code} generated`);
    }
    $("#recordModal").close();form.reset();form.dataset.editId="";
  }catch(error){
    console.error("record_save_failed",error);
    toast(error.message||"The record could not be saved.");
  }finally{saveButton.disabled=false}
});

const now=new Date();$("#todayLabel").textContent=new Intl.DateTimeFormat("en-GH",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(now);const days=Math.max(0,Math.ceil((new Date("2026-11-07T00:00:00+00:00")-now)/86400000));$("#sidebarCountdown").textContent=`${days} day${days===1?"":"s"} remaining`;
renderStats();renderTasks();renderCalendar();renderMedia();renderTributes();syncTributes();
const saved=localStorage.getItem("oaTeamsProfile");if(saved){try{const profile=JSON.parse(saved);applyProfile(profile);showStage("app");registerProfile(profile).then(serverProfile=>{localStorage.setItem("oaTeamsProfile",JSON.stringify(serverProfile));applyProfile(serverProfile)}).catch(error=>console.error("profile_sync_failed",error))}catch{localStorage.removeItem("oaTeamsProfile")}}
