FROM nginx:alpine
COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html tributes.html /usr/share/nginx/html/
COPY css /usr/share/nginx/html/css
COPY js /usr/share/nginx/html/js
COPY logo /usr/share/nginx/html/logo
COPY web-pictures /usr/share/nginx/html/web-pictures
COPY booklet-assets /usr/share/nginx/html/booklet-assets
COPY event-assets /usr/share/nginx/html/event-assets
